[tool.poetry]
name = "starfield-quicksave-backup"
version = "0.1.0"
description = "Starfield automatic quicksave and backup utility"
authors = ["Danny Stewart <danny@stewart.cc>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pynput = "^1.7.7"
pywin32 = "^307"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
